version: "3"
services:
 postgres_cadastro: 
    image: postgres:12.2
    container_name: postgres_cadastro
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-crud
