version: "3"
services:
 postgres_cadastro:  #http://localhost:8080/swagger-ui
    image: postgres:12.2
    container_name: postgres_cadastro
    ports:
      - 5437:5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-crud
 keycloak_ifood: #http://localhost:8180
    image: jboss/keycloak:9.0.2
    container_name: keycloak_ifood
    environment:
         - KEYCLOAK_USER=admin
         - KEYCLOAK_PASSWORD=admin
    ports:
      - 8180:8080
 jaeger_ifood: #http://localhost:16686
    image: jaegertracing/all-in-one:1.18
    container_name: jaeger_ifood
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
 prometheus_ifood: #http://localhost:9090
    build:
       context: . 
       dockerfile: Dockerfile.prometheus
    container_name: prometheus_ifood
    ports:
      - 9090:9090
    network_mode: "host"
 grafana_ifood: #http://localhost:3000
    container_name: grafana_ifood
    image: grafana/grafana:6.5.0
    network_mode: "host"
    ports:
      - 3000:3000

