version: "3"
services:
 postgres_cadastro: 
    image: postgres:12.2
    container_name: postgres_cadastro
    ports:
      - 5437:5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-crud
 keycloak_ifood:
    image: jboss/keycloak:9.0.2
    container_name: keycloak_ifood
    environment:
         - KEYCLOAK_USER=admin
         - KEYCLOAK_PASSWORD=admin
    ports:
      - 8180:8080

